<template>
  <div class="contact">
    <div class="container">
      <img class="image" alt="" src="../assets/maria_contact.jpg">
      <div class="form-container">
        <h1 class="title">contact Me</h1>
        <form class="form">
          <input 
            v-model="smtp.name" 
            v-on:input="validateForm" 
            ref="name" 
            placeholder="name"
            />
          <input 
            v-model="smtp.email" 
            v-on:input="validateForm" 
            ref="email" 
            placeholder="email"
            />
          <input 
            v-model="smtp.subject" 
            v-on:input="validateForm" 
            ref="subject" 
            placeholder="subject"
            />
          <textarea 
            v-model="smtp.message" 
            v-on:input="validateForm" 
            ref="message" 
            placeholder="Message"
            />
          <div class='button-row'>
            <button v-on:click="handleClick">{{ button }}</button>
            <span>{{ status }}</span>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script>

  import axios from 'axios'

  export default {
    name: 'contact',
    data () { 
      return {
        sendAttempted: false,
        button: 'send',
        smtp: {
          name: '',
          email: '',
          subject: '',
          message: '',
        },
        status: '',
      }
    },
    methods: {
      handleClick () {
        let self = this;
        this.sendAttempted = true;
        let k = this.validateForm();
        if (k) {
          this.$refs[k].focus();
        } else {
          this.button = '...';
          this.status = '';
          let data = {
            email: this.smtp.email,
            subject: this.smtp.subject,
            message: `
              --this is an autogenerated email from maryfromla.com/contact--
  
              from: ${this.smtp.name}
              email: ${this.smtp.email}
              message: ${this.smtp.message}
            `,
            }
          axios.post('https://7vr0g56e12.execute-api.us-west-2.amazonaws.com/prod/SMTP_Mailer', data)
            .then((status) => {
              status.status === 200 && (this.status = 'message sent')
              this.button = 'send'
              this.smtp = {
                name: '',
                email: '',
                subject: '',
                message: '',
              }
            })
            .catch((err) => {
              console.warn(err);
              this.status = 'error sending message'
              this.button = 'send'
            })
        }
      },
      validateForm () {
        let entries = Object.entries({...this.smtp});
        let error = '';
        let key = '';
        for (const [k, v] of entries) {
          if (k === 'email' && v.length && !error) {
            if(!/(.+)@(.+){2,}\.(.+){2,}/.test(v)) {
              error = `error: invalid email format`
              key = k;
            }
          }
          if (!v.length && !error) {
            error = `error: ${k} is a required field`
            key = k;
          }
        }
        if (this.sendAttempted) {
          this.status = error;
        }
        return key;
      },
    },
  }
</script>


<style scoped>
  .contact {
    min-height: 100vh;
    display: flex;
    /* padding: 20px; */
    padding-top: 80px;

  }

  .container {
    display: flex;
    /* flex-wrap: wrap; */
    /* justify-content:space-between; */
    height: 110vh;
    overflow: hidden;
    width: 100vw;
  }

  .image {
    /* width: 70%; */
    /* max-width: 70vw; */
    object-fit: cover;
    object-position: top;
    position: relative;
    height: 150vh;
    max-width: 50vw;
    /* margin: 30px; */
    /* box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); */
    /* border-radius: 8px; */
  }

  .form-container {
    max-width: 50vw;
    background-color: rgba(245, 245, 245, 0.815);
    display: flex;
    flex-direction: column;
    width: 100%;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.3);
    /* border: 3px solid rgb(255, 221, 110); */
    border-radius: 8px;
    margin: 30px 60px;
    height: 80vh;
    max-height: 600px;
    /* max-width: 620px; */

  }

  .form {
    width: 80%;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
  }

  .title {
    font-size: 50px;
    padding: 40px  90px;
    display: flex;
    justify-content: center;
    align-items: center;
    font-family: 'Major Mono Display', monospace;
    font-weight: 100;
  }

  input, textarea {
    outline: none;
    background-color: rgb(255, 255, 255);
    -webkit-appearance: none;
    -moz-appearance: none;
    border: 5px solid rgb(255, 255, 255);
    color: black;
    margin: 0 0 10px;
    width: 100%;
    padding: 6px;
    text-rendering: auto;
    letter-spacing: normal;
    word-spacing: normal;
    text-transform: none;
    text-indent: 0px;
    text-shadow: none;
    display: inline-block;
    text-align: start;
    transition: .3s;
    border-radius: 3px;
    font-size: 14px;
    font-weight: 100;
  }

  input:-webkit-autofill,
  input:-webkit-autofill:hover, 
  input:-webkit-autofill:focus, 
  input:-webkit-autofill:active  {
    -webkit-box-shadow: 0 0 0 30px white inset !important;
    box-shadow: 0 0 0 30px white inset !important;
}

  textarea {
    -webkit-appearance: textarea;
    -webkit-rtl-ordering: logical;
    cursor: text;
    white-space: pre-wrap;
    overflow-wrap: break-word;
    -webkit-appearance: none;
    -moz-appearance: none;
    width: 100%;
    resize: none;
    height: 120px;
  }

  input:focus, textarea:focus {
    transition: .3s;
    border: 5px solid #DDD6F3;
  }

  ::-webkit-input-placeholder { /* Chrome/Opera/Safari */
    color: black;
  font-family: 'Major Mono Display', monospace;
  
  }
  ::-moz-placeholder { /* Firefox 19+ */
    color: black;
    font-family: 'Major Mono Display', monospace;
  }
  :-ms-input-placeholder { /* IE 10+ */
    color: black;
    font-family: 'Major Mono Display', monospace;
  }
  :-moz-placeholder { /* Firefox 18- */
    color: black;
    font-family: 'Major Mono Display', monospace;
  }

  button {
    height: 40px;
    width: 100px;
    background-color: #DDD6F3;
    color: white;
    font-weight: bolder;
    cursor: pointer;
    margin: 0;
    transition: .3s;
    outline: none;
    border: 3px solid #DDD6F3;
    border-radius: 3px;
    font-family: 'Major Mono Display', monospace;
    font-size: 18px;

  }

  button:focus {
    /* box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); */
    border: 3px solid rgb(255, 255, 255);

  }

  button:active {
    box-shadow: none;
    /* transition: .3s; */
  }

  .button-row {
    display: flex;
    align-items: center;
  }

  .button-row span {
    margin: auto;
    font-family: 'Major Mono Display', monospace;
  }

    /* Tablet */
  @media only screen and (max-width : 1040px) {
    .image {
      max-width: 40vw;
    }
    .contact, .container {
      height: 100vh;
    }

    .form-container {
      margin: auto;
    }
  }

  @media only screen and (max-width : 1040px) and  (min-height: 1000px) {
    .form-container {
      position: relative;
      top: -40px;
    }
  }


  /* Mobile */
  @media only screen and (max-width : 600px) {
    .image {
      display: none;
    }
    .form-container {
      margin: auto;
      max-width: 90vw;
      position: relative;
      top: -40px;
    }
  }

      /* XS Mobile */
  @media only screen and (max-height : 600px) {
    .title {
      font-size: 30px;
      margin: 0px;
      padding: 30px;
    }
  }

</style>